// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEvOjDX5WDwHCjIercSqOpQHWDbUr-tkU',
    appId: '1:480940217095:web:31dec95e49818c32a0aba2',
    messagingSenderId: '480940217095',
    projectId: 'login-register-pages-986f1',
    authDomain: 'login-register-pages-986f1.firebaseapp.com',
    storageBucket: 'login-register-pages-986f1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy9Nlvlrui5XIsS279LUMVnbO0WnPKuVI',
    appId: '1:480940217095:android:191b9cd75a33611aa0aba2',
    messagingSenderId: '480940217095',
    projectId: 'login-register-pages-986f1',
    storageBucket: 'login-register-pages-986f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8oVzeCSVpNZJ43KDFqtvr9Se0b4sEFmc',
    appId: '1:480940217095:ios:2472fa3fdc5205e3a0aba2',
    messagingSenderId: '480940217095',
    projectId: 'login-register-pages-986f1',
    storageBucket: 'login-register-pages-986f1.appspot.com',
    iosBundleId: 'com.example.newumna',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8oVzeCSVpNZJ43KDFqtvr9Se0b4sEFmc',
    appId: '1:480940217095:ios:2472fa3fdc5205e3a0aba2',
    messagingSenderId: '480940217095',
    projectId: 'login-register-pages-986f1',
    storageBucket: 'login-register-pages-986f1.appspot.com',
    iosBundleId: 'com.example.newumna',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEvOjDX5WDwHCjIercSqOpQHWDbUr-tkU',
    appId: '1:480940217095:web:ec58d3740b9b763da0aba2',
    messagingSenderId: '480940217095',
    projectId: 'login-register-pages-986f1',
    authDomain: 'login-register-pages-986f1.firebaseapp.com',
    storageBucket: 'login-register-pages-986f1.appspot.com',
  );
}
